### ISSUE TITLE
Odoo 13 plugin doesn't work

### ISSUE THREAD

**Issue by primeworks** [Flutterwave/rave-odoo-erp#7]
Hi,
I enjoyed the module for Odoo 12, but this version keeps showing an error when the payment button is clicked.
Please help.

**Comment by williemwewa** [comment]
Hello. Did you manage to have this error resolved?

**Comment by primeworks** [comment]
Hi,
No I didn’t get it resolved. I reached out to Flutterwave and there was no response.

**Comment by bajoski34** [comment]
@primeworks @williemwewa The issues have been resolved

**Comment by primeworks** [comment]
Okay @bajoski34 
I'll test it right away.

**Comment by primeworks** [comment]
Hello @bajoski34 
I uploaded the code to the database but when I tried to install it I kept getting an error. Is that expected?

**Comment by bajoski34** [comment]
> Hello @bajoski34
> I uploaded the code to the database but when I tried to install it I kept getting an error. Is that expected?

what error are your referring to ?

**Comment by primeworks** [comment]
Hello @bajoski34 
I didn't read the file. I did and figured out what I did wrong. Thanks.

**Comment by amos994** [comment]
having the same challenge, how did you resolve it?
