### ISSUE TITLE
Close Behaviour: Keeps other scripts waiting

### ISSUE THREAD

**Issue by EwetoyeIbrahim** [Flutterwave/rave-odoo-erp#8]
Problem: Whenever the payment popup is closed without any payment action, the user goes back to the payment page but the pay now button and all other scripts (that need the payment response) keeps waiting, as such the user may not be able to choose other payment options (and possibly some other dependent actions) unless the page is reloaded. This is not what we want how customers to figure out on their own.

Solution: I will be submitting a pull request that solves this now since it can be solved by simply reloading the payment page on close.

**Comment by primeworks** [comment]
Hi. Is this fix for Odoo v13?

**Comment by EwetoyeIbrahim** [comment]
We are using Odoo12, but I edited two files on the master branch, which
suggests it's for both 12 and 13. But note that its on the master branch
not on rave-odoo-erp-13.0 branch.


*EwetoyeIbrahim.github.io <https://EwetoyeIbrahim.github.io>Knowing is not
enough; we must apply.*
